# localhost
# spring:
#   kafka:
#     kafka-server: localhost:9092
#     consumer:
#         group-id: product-group
#         auto-offset-reset: earliest

# k8s
spring:
  kafka:
    bootstrap-servers: kafka-service:9092   # ✅ 이게 정식 키

    consumer:
      group-id: product-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

        